name: salon_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.6.1
  smooth_page_indicator: ^1.0.0+2

  shared_preferences: ^2.0.13
  flutter_bloc: ^8.1.2
  dotted_border: ^2.0.0+3
  bloc: ^8.0.2
  hexcolor: ^2.0.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/Poppins-Black.ttf

