// class ChooseBarbersModel {
//   bool? status ;
//   String? message;
//   Data? data;
//
//   ChooseBarbersModel.fromJson(Map<String, dynamic> json) {
//     status = json['status'];
//     message = json['message'];
//     data =  Data.fromJson(json['data']);
//   }
// }
//
// class Data {
//   String? name;
//
//
//   Data.fromJson(Map<String, dynamic> json) {
//     name = json['name'];
//
//   }
// }
class Autogenerated {
 late List<Data> data;
 late int status;
 late String message;

  Autogenerated({required this.data, required this.status, required this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data =  <Data>[];
      json['data'].forEach((v) {
        data.add(Data.fromJson(v));
      });
    }
    status = json['status'];
    message = json['message'];
  }
}

class Data {
 late int id;
 late String name;
 late String phone;
 late String email;

  Data({required this.id, required this.name, required this.phone, required this.email});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    phone = json['phone'];
    email = json['email'];
  }

  // Map<String, dynamic> toJson() {
  //   final Map<String, dynamic> data = new Map<String, dynamic>();
  //   data['id'] = this.id;
  //   data['name'] = this.name;
  //   data['phone'] = this.phone;
  //   data['email'] = this.email;
  //   return data;
  // }
}